APIFY_API_KEY = "apify_api_W4VogoZ8sw9jMvN60dddFtOUaO4a8t3eorU2"
TASK_ID = "S3l5dfGYvZTbXzWNr"  # dev
API_URL = "https://api.apify.com/v2/actor-tasks/mr.joshuagordon~instagram-post-scraper-task---dev/runs/last/dataset/items"
API_URL = "https://api.apify.com/v2/actor-tasks/mr.joshuagordon~scrape-popular-triathlon-instagrams/runs/last/dataset/items"
REDDIT_CLIENT_ID = "ZdbVm7-3Ve4UyNXtlPJvEg"
REDDIT_CLIENT_SECRET = "1hMDppbiq2bUb_qAmWa5m3ve7HA2bw"
YT_API_KEY = 'AIzaSyBtawvVaF5S4ZBKWaaoY2IXaFSTQZ42rOo'
DATA_PATH = "/data/" # render remote
#DATA_PATH = "data/"  # local
# main TASK_ID =  #"FOhHAQ8pPrqHrdFTY"